FROM nvidia/cuda:11.8.0-cudnn8-devel-ubuntu22.04

USER root

COPY ./requirements.txt /tmp
WORKDIR /workspace

RUN apt-get update && apt-get -y upgrade
RUN apt-get update && apt-get install -y curl python3 python3-pip

EXPOSE 8888

RUN pip install -r /tmp/requirements.txt
CMD ["jupyter", "lab", "--ip=0.0.0.0", "--port=8888", "--allow-root", "--NotebookApp.token='0424'"]
