  jupyter-lab:
    image: osaka-docker.pkg.dev/colab-images/public/runtime
    ports:
      - "0.0.0.1:9000:9999"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
