"""Regenerate requirements.txt from the third-party imports actually used in the repo.

Usage (repo root):
    python scripts/update_requirements.py          # rewrite requirements.txt
    python scripts/update_requirements.py --check  # exit 1 if it is out of date

Rules: imports are found by AST scan of git-tracked .py files. Version specifiers already in
requirements.txt are preserved (edit them by hand to pin). New packages are unpinned. CUDA extras live in requirements-cuda.txt.
"""
import ast
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
REQ = ROOT / "requirements.txt"
# import name -> PyPI distribution (only where they differ or must be forced in)
PYPI = {"kagglesdk": "kaggle"}
# Imports that are never PyPI deps (local modules, sibling scripts, notebook artefacts).
IGNORE = {"src", "scripts", "tests", "file", "held"}
ALWAYS = ["jax", "flax", "optax", "gymnax", "craftax", "numpy", "pandas", "matplotlib", "kaggle"]  # core stack, even if only imported lazily
HEADER = (
    "# AUTO-GENERATED by scripts/update_requirements.py (pre-commit hook). Edit specifiers by hand\n"
    "# to pin; they are preserved. For NVIDIA GPUs use: pip install -r requirements-cuda.txt\n"
)


def tracked_py():
    out = subprocess.run(["git", "ls-files", "*.py"], cwd=ROOT, capture_output=True, text=True, check=True)
    return [ROOT / p for p in out.stdout.split() if not p.startswith(("output", "kaggle_kernel"))]


def imported_tops(files):
    tops = set()
    for f in files:
        try:
            tree = ast.parse(f.read_text(encoding="utf-8"))
        except (SyntaxError, UnicodeDecodeError, OSError):
            continue
        for n in ast.walk(tree):
            if isinstance(n, ast.Import):
                tops.update(a.name.split(".")[0] for a in n.names)
            elif isinstance(n, ast.ImportFrom) and n.level == 0 and n.module:
                tops.add(n.module.split(".")[0])
    return tops


def local_modules(files):
    return {f.stem for f in files} | {p.name for p in ROOT.iterdir() if p.is_dir()}


def existing_specs():
    specs = {}
    if REQ.exists():
        for line in REQ.read_text(encoding="utf-8").splitlines():
            m = re.match(r"^([A-Za-z0-9_.\-]+)(.*)$", line.strip())
            if m and not line.startswith("#"):
                specs[m.group(1).lower()] = m.group(2).strip()
    return specs


def build():
    files = tracked_py()
    stdlib = set(sys.stdlib_module_names)
    third = {t for t in imported_tops(files) if t not in stdlib and t not in IGNORE and t not in local_modules(files)}
    dists = {PYPI.get(t, t).lower() for t in third} | set(ALWAYS)
    dists.discard("jaxlib")
    old = existing_specs()
    lines = []
    for d in sorted(dists):
        spec = old.get(d)
        if spec is None:
            spec = ""  # unpinned by default: a local (e.g. Py3.14) version floor could break Kaggle/cloud
        lines.append(f"{d}{spec}")
    return HEADER + "\n".join(lines) + "\n"


def main():
    new = build()
    cur = REQ.read_text(encoding="utf-8") if REQ.exists() else ""
    if "--check" in sys.argv:
        if new != cur:
            print("requirements.txt is out of date; run: python scripts/update_requirements.py")
            return 1
        return 0
    if new != cur:
        REQ.write_text(new, encoding="utf-8", newline="\n")
        print("requirements.txt updated")
    return 0


if __name__ == "__main__":
    sys.exit(main())
